### ISSUE TITLE
Some questions from the biorxiv preprint

### ISSUE THREAD

**Issue by adriaaula** [akrinos/2023-euk-diversity#1]
Hello Arianna, 

With @aleixop we read your preprint and we liked very much the topic! How to annotate taxonomically the fragmentary data that most of the time we have at our hands is a hard topic. Looking forward to use your approach. 

We had some questions regarding the figures that you may be able to clarify. 

For Figure 3, have you checked how the metatranscriptomics relative abundance pattern would change after performing the tax aliquot approach? That is, in Fig3A, if we included the same plot below the missanotated transcriptome using the taxonomy from Fig6A, how would the pattern change? 

For Figure 6, it was difficult for us to relate the numbers written in the text to the bars in the plot. For example, for Figure 6A you say that “the tax-aliquots algorithm expands the number of sequences that can be linked to the genus Phaeocystis by 47% when a matching species or strain reference is unavailable”. Where is this number represented in the plot? Additionally, do the plain gray zones (without stripes) in the plot represent sequences that had a tax annotation with BLAST-LCA and not with tax-aliquots (and thus we lost)?

We did not understand the Supplementary Figure 9. Specifically, we are surprised by the huge difference between these results. 

You state this: 

> A significant decision for ‘omics researchers is whether metatranscriptome
annotation is applied to ORFs using the blastp algorithm or full contigs using the blastx
algorithm: the blastx algorithm will translate the nucleotide sequence into all six possible
reading frames and return the best hits to any of those reading frames, resulting in
a single taxonomic annotation per contig

Could you in any case elaborate a little on that? 

Thanks a ton for your time!

**Comment by akrinos** [comment]
Hi @adriaaula - thank you _so_ much for commenting here! I really appreciate your interest in and feedback on my work. Apologies for the delayed response!

**Figure 3** - with tax-aliquots, we wanted to be careful about showing new community composition plots, specifically because tax-aliquots demonstrates the uncertainty in annotating community composition with incomplete references. But it is a good avenue to show this more concretely and something we are working on!
**Figure 6** - thank you for this feedback. In the subsequent lines of text after the 47%, we explain what we mean by this; the 47% increase is for _Phaeocystis_-containing clusters using the free-living database (corresponding to the middle set of bars in the top barchart). The tricky thing about interpreting the gray area is that tax-aliquots conservatively assigns annotations, so while currently this is the best we can do with tax-aliquots, we are hoping to present an improved hybrid approach that does both (but also takes into account the ideas we present in the paper about taxonomic ambiguity). Stay tuned for that hopefully soon!
**Supplementary Figure 9** - this is a different, but related issue - when we use the `blastx` algorithm, we actually get a whole lot more of the assigned reads annotated than when we use `blastp` against predicted proteins. This tends to be true in datasets like BATS that are highly diverse. It highlights shortcomings in predicting protein sequences from a whole community at once, especially when ordinary protein prediction methods might be inadequate. That was also our meaning with the text you quoted - if we _don't_ predict proteins first, we annotate nucleotide sequences with proteins from the database, but don't first throw away sequences from which an open reading frame can't be predicted. 

We hope to engage with you more about this topic in the future! Thanks again!

**Comment by adriaaula** [comment]
Thanks a ton for your response, everything is way clearer :)
